#!/usr/bin/env bash
set -e

# =========================================================
# Build OpenCV with CUDA/cuDNN support
# =========================================================

# (your existing build logic stays here)
# e.g. cmake, make, make install ...
# ---------------------------------------------------------
# Example end of build:
# sudo make -j$(nproc)
# sudo make install

echo "✅ OpenCV CUDA/cuDNN build completed."

# =========================================================
# Configure runtime environment for OpenCV
# =========================================================

# Detect system GLib library location
GLIB_PATH=$(whereis libglib-2.0.so.0 | awk '{print $2}')

if [ -z "$GLIB_PATH" ]; then
    echo "❌ Could not locate system libglib-2.0.so.0."
    echo "Please install 'libglib2.0-0' and rerun this script."
    exit 1
fi

echo "🔹 Found system GLib at: $GLIB_PATH"

# Create a launcher script to run Python with the correct GLib preloaded
LAUNCHER_PATH="$HOME/.local/bin/opencv_py"
mkdir -p "$(dirname "$LAUNCHER_PATH")"

cat <<EOF > "$LAUNCHER_PATH"
#!/usr/bin/env bash
# Auto-generated by build_opencv_cuda.sh on $(date)
# Ensures correct GLib for OpenCV GUI support in Conda environments

export LD_PRELOAD=$GLIB_PATH
exec python3 "\$@"
EOF

chmod +x "$LAUNCHER_PATH"

echo "🚀 Created Python launcher for OpenCV at: $LAUNCHER_PATH"
echo
echo "To run Python with proper OpenCV support, use:"
echo "  opencv_py myscript.py"
echo
echo "If you want this to be available globally, add this to your ~/.bashrc:"
echo "  export PATH=~/.local/bin:\$PATH"
echo

# Optional: test automatically (uncomment to verify import after build)
LD_PRELOAD="$GLIB_PATH" python3 -c "import cv2; print('OpenCV version:', cv2.__version__)"